Instance: HereditaryCancerTestingGenomicStudyAnalysis
InstanceOf: Procedure
Usage: #example
* meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis"
* extension[0].extension[0].url = "description"
* extension[=].extension[=].valueString = "protein-coding and exon-splicing regions"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1101 "BRCA2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:583 "APC"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:795 "ATM"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:904 "AXIN2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:950 "BAP1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:952 "BARD1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1076 "BMPR1A"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1100 "BRCA1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:20473 "BRIP1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1748 "CDH1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1773 "CDK4"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:1787 "CDKN2A"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:16627 "CHEK2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:2509 "CTNNA1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:3700 "FH"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:27310 "FLCN"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:5112 "HOXB13"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7010 "MEN1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7029 "MET"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7127 "MLH1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7325 "MSH2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7326 "MSH3"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7329 "MSH6"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7527 "MMAYH"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:8028 "NTHL1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:26144 "PALB2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9122 "PMS2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9588 "PTEN"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9820 "RAD51C"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9823 "RAD51D"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:10680 "SDHA"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:10681 "SDHB"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:10682 "SDHC"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:10683 "SDHD"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:6770 "SMAD4"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:11389 "STK11"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:11998 "TP53"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:12362 "TSC1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:12363 "TSC2"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:12687 "VHL"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:3236 "EGFR"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:11529 "EPCAM"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:2001 "GREM1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:7105 "MITF"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9177 "POLE"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9175 "POLD1"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:9967 "RET"
* extension[=].extension[+].url = "studied"
* extension[=].extension[=].valueCodeableConcept = $genenames#HGNC:11730 "TERT"
* extension[=].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-regions"
* extension[+].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-method-type"
* extension[=].valueCodeableConcept = $genomic-study-method-type-cs#sequence-analysis-of-the-entire-coding-region "Sequence analysis of the entire coding region"
* extension[+].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-genome-build"
* extension[=].valueCodeableConcept = $loinc#LA26806-2 "GRCh38"
* extension[+].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-specimen"
* extension[=].valueReference = Reference(SpecimenBloodFemale)
* extension[+].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-focus"
* extension[=].valueReference = Reference(PatientFemale)
* extension[+].extension[0].url = "type"
* extension[=].extension[=].valueCodeableConcept = $genomic-study-data-format-cs#vcf "VCF"
* extension[=].extension[+].url = "file"
* extension[=].extension[=].valueReference = Reference(DocumentReference/HereditaryCancerTestingVCF)
* extension[=].url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomic-study-analysis-output"
* status = #completed
* category = $observation-category#laboratory "Laboratory"
* subject = Reference(PatientFemale)
* performedDateTime = "2023-02-02T01:01:10-06:00"
* note[0].text = "Genes Analyzed: Sequencing (seq) and large rearrangement analyses were performed for all coding exons in the following genes, unless otherwise indicated: APC, ATM, AXIN2, BAP1, BARD1, BMPR1A, BRCA1, BRCA2, BRIP1, CDH1, CDK4, CDKN2A, CHEK2, CTNNA1, FH, FLCN, HOXB13 (seq only), MEN1, MET, MLH1, MSH2, MSH3 (excluding repetitive portions of exon 1), MSH6, MMAYH, NTHL1, PALB2, PMS2, PTEN, RAD51C, RAD51D, SDHA, SDHB, SDHC, SDHD, SMAD4, STK11, TP53, TSC1, TSC2, VHL. Limited promoter regions may also be analyzed for large rearrangements."
* note[+].text = "Sequencing (seq) and/or large rearrangement (LR) analyses were performed only for the gene portions indicated in parenthesis for the following genes: EGFR (exons 18-21, seq and LR), EPCAM (exons 8-9, LR only), GREM1 (exon 1 and upstream regulatory regions, LR only), MITF (c.952, seq only), POLE (exonuclease domain, seq only), POLD1 (exonuclease domain, seq only), RET (exons 5, 8, 10, 11, 13-16 seq and LR), TERT (promoter c.DNA -1 to -70, seq only). Other genes not analyzed with this test may also be associated with cancer."
* note[+].text = "Indication for Testing: It is our understanding that this individual was identified for testing due to a personal or family history suggestive of a hereditary predisposition for cancer."
* note[+].text = "Associated Cancer Risks and Clinical Management: The \"HereditaryCancerTesting Management Tool\" associated with this report provides a summary of cancer risk and professional society medical management guidelines that may be useful in developing a plan for this patient based on any clinically significant test results and/or reported personal/family history. In some cases, a HereditaryCancerTesting Management Tool cannot be provided, such as when the result has a special interpretation or includes a mutation with unusual characteristics."
* note[+].text = "Analysis Description: The Technical Specifications summary (myriad.com/technical-specifications) describes the analysis, method, performance, nomenclature, and interpretive criteria of this test. Current testing technologies are unable to definitively determine whether a variant is germline or somatic in origin, which may significantly impact risk estimates and medical management; therefore, these results should be correlated with this patient's personal and family history. The interpretation of this test may also be impacted if the patient has a hematologic malignancy or an allogeneic bone marrow transplant."