Instance: PrenatalCollectionBundlePartnered
InstanceOf: Bundle
Usage: #example
* type = #collection
* entry[0].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PractitionerLabDirector"
* entry[=].resource = PractitionerLabDirector
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PatientMale"
* entry[=].resource = PatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PatientFemale"
* entry[=].resource = PatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant1CNVFactorXiDeficiencyPatientMale"
* entry[=].resource = PrenatalVariant1CNVFactorXiDeficiencyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantFactorXiDeficiencyPatientFemale"
* entry[=].resource = PrenatalVariantFactorXiDeficiencyPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantPrimaryHyperoxaluriaPatientMale"
* entry[=].resource = PrenatalVariantPrimaryHyperoxaluriaPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantGlycogenStorageDiseaseTypePatientMale"
* entry[=].resource = PrenatalVariantGlycogenStorageDiseaseTypePatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantPrimaryHyperoxaluriaPatientFemale"
* entry[=].resource = PrenatalVariantPrimaryHyperoxaluriaPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantGlycogenStorageDiseaseTypePatientFemale"
* entry[=].resource = PrenatalVariantGlycogenStorageDiseaseTypePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskFactorXiDeficiencyPatientMale"
* entry[=].resource = PrenatalResidualRiskFactorXiDeficiencyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskFactorXiDeficiencyPatientFemale"
* entry[=].resource = PrenatalResidualRiskFactorXiDeficiencyPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGroupPatientFemaleandPatientMale"
* entry[=].resource = PrenatalGroupPatientFemaleandPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskPrimaryHyperoxaluriaPatientMale"
* entry[=].resource = PrenatalResidualRiskPrimaryHyperoxaluriaPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant1SNPHereditaryHemochromatoPatientMale"
* entry[=].resource = PrenatalVariant1SNPHereditaryHemochromatoPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskGlycogenStorageDiseasePatientMale"
* entry[=].resource = PrenatalResidualRiskGlycogenStorageDiseasePatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PractitionerOrderingProvider"
* entry[=].resource = PractitionerOrderingProvider
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisFactorXiDeficiencyPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisFactorXiDeficiencyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisHereditaryHemochromatoPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisHereditaryHemochromatoPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisGlycogenStorageDiseasePatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisGlycogenStorageDiseasePatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant2FragileXSyndromePatientFemale"
* entry[=].resource = PrenatalVariant2FragileXSyndromePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant1FragileXSyndromePatientFemale"
* entry[=].resource = PrenatalVariant1FragileXSyndromePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskPrimaryHyperoxaluriaPatientFemale"
* entry[=].resource = PrenatalResidualRiskPrimaryHyperoxaluriaPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant2SNPHereditaryHemochromatoPatientFemale"
* entry[=].resource = PrenatalVariant2SNPHereditaryHemochromatoPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant1SNPHereditaryHemochromatoPatientFemale"
* entry[=].resource = PrenatalVariant1SNPHereditaryHemochromatoPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskGlycogenStorageDiseasePatientFemale"
* entry[=].resource = PrenatalResidualRiskGlycogenStorageDiseasePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisFragileXSyndromePatientFemale"
* entry[=].resource = PrenatalGenomicStudyAnalysisFragileXSyndromePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisFactorXiDeficiencyPatientFemale"
* entry[=].resource = PrenatalGenomicStudyAnalysisFactorXiDeficiencyPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisHereditaryHemochromatoPatientFemale"
* entry[=].resource = PrenatalGenomicStudyAnalysisHereditaryHemochromatoPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisGlycogenStorageDiseasePatientFemale"
* entry[=].resource = PrenatalGenomicStudyAnalysisGlycogenStorageDiseasePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaPatientFemale"
* entry[=].resource = PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePostRiskFactorXiDeficiencyCouple"
* entry[=].resource = PrenatalReproductivePostRiskFactorXiDeficiencyCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaCouple"
* entry[=].resource = PrenatalGenomicStudyAnalysisPrimaryHyperoxaluriaCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisHereditaryHemochromatoCouple"
* entry[=].resource = PrenatalGenomicStudyAnalysisHereditaryHemochromatoCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisGlycogenStorageDiseaseCouple"
* entry[=].resource = PrenatalGenomicStudyAnalysisGlycogenStorageDiseaseCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisFactorXiDeficiencyCouple"
* entry[=].resource = PrenatalGenomicStudyAnalysisFactorXiDeficiencyCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpPrimaryHyperoxaluriaPatientMale"
* entry[=].resource = PrenatalDiagImpPrimaryHyperoxaluriaPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpHereditaryHemochromatoPatientMale"
* entry[=].resource = PrenatalDiagImpHereditaryHemochromatoPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpGlycogenStorageDiseasePatientMale"
* entry[=].resource = PrenatalDiagImpGlycogenStorageDiseasePatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpFactorXiDeficiencyPatientMale"
* entry[=].resource = PrenatalDiagImpFactorXiDeficiencyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalSpecimenPatientMale"
* entry[=].resource = PrenatalSpecimenPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/Organization"
* entry[=].resource = Organization
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalServiceRequestCouple"
* entry[=].resource = PrenatalServiceRequestCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyPatientMale"
* entry[=].resource = PrenatalGenomicStudyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpFragileXSyndromePatientFemale"
* entry[=].resource = PrenatalDiagImpFragileXSyndromePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpPrimaryHyperoxaluriaPatientFemale"
* entry[=].resource = PrenatalDiagImpPrimaryHyperoxaluriaPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpHereditaryHemochromatoPatientFemale"
* entry[=].resource = PrenatalDiagImpHereditaryHemochromatoPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpGlycogenStorageDiseasePatientFemale"
* entry[=].resource = PrenatalDiagImpGlycogenStorageDiseasePatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpFactorXiDeficiencyPatientFemale"
* entry[=].resource = PrenatalDiagImpFactorXiDeficiencyPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalSpecimenPatientFemale"
* entry[=].resource = PrenatalSpecimenPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyPatientFemale"
* entry[=].resource = PrenatalGenomicStudyPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpFragileXSyndromeCouple"
* entry[=].resource = PrenatalReprDiagImpFragileXSyndromeCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpHereditaryHemochromatoCouple"
* entry[=].resource = PrenatalReprDiagImpHereditaryHemochromatoCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpFactorXiDeficiencyCouple"
* entry[=].resource = PrenatalReprDiagImpFactorXiDeficiencyCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRecommendedFollowup1PatientMale"
* entry[=].resource = PrenatalRecommendedFollowup1PatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRecommendedFollowup1PatientFemale"
* entry[=].resource = PrenatalRecommendedFollowup1PatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyCouple"
* entry[=].resource = PrenatalGenomicStudyCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicReportPatientMale"
* entry[=].resource = PrenatalGenomicReportPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicReportPatientFemale"
* entry[=].resource = PrenatalGenomicReportPatientFemale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePreRiskFactorXiDeficiencyCouple"
* entry[=].resource = PrenatalReproductivePreRiskFactorXiDeficiencyCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalNegativeReprRiskCouple"
* entry[=].resource = PrenatalNegativeReprRiskCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicReportCouple"
* entry[=].resource = PrenatalGenomicReportCouple
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRelatedPersonPatientMale"
* entry[=].resource = PrenatalRelatedPersonPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRelatedPersonPatientFemale"
* entry[=].resource = PrenatalRelatedPersonPatientFemale