Instance: PrenatalCollectionBundleSingle
InstanceOf: Bundle
Usage: #example
* type = #collection
* entry[0].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PractitionerLabDirector"
* entry[=].resource = PractitionerLabDirector
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PatientMale"
* entry[=].resource = PatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariant1SNPAlpha1ADPatientMale"
* entry[=].resource = PrenatalVariant1SNPAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalVariantAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalVariantFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalVariantFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskAlpha1ADPatientMale"
* entry[=].resource = PrenatalResidualRiskAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalResidualRiskAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalResidualRiskFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalResidualRiskFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePostRiskAlpha1ADPatientMale"
* entry[=].resource = PrenatalReproductivePostRiskAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePostRiskAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalReproductivePostRiskAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePostRiskFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalReproductivePostRiskFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PractitionerOrderingProvider"
* entry[=].resource = PractitionerOrderingProvider
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisAlpha1ADPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyAnalysisAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalGenomicStudyAnalysisAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpAlpha1ADPatientMale"
* entry[=].resource = PrenatalDiagImpAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalDiagImpFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalDiagImpAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalDiagImpAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpAlpha1ADPatientMale"
* entry[=].resource = PrenatalReprDiagImpAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalReprDiagImpAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReprDiagImpFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalReprDiagImpFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalSpecimenPatientMale"
* entry[=].resource = PrenatalSpecimenPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/Organization"
* entry[=].resource = Organization
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalServiceRequestPatientMale"
* entry[=].resource = PrenatalServiceRequestPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRecommendedFollowup2PatientMale"
* entry[=].resource = PrenatalRecommendedFollowup2PatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalRecommendedFollowup1PatientMale"
* entry[=].resource = PrenatalRecommendedFollowup1PatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicStudyPatientMale"
* entry[=].resource = PrenatalGenomicStudyPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePreRiskFamilialHyperinsulinismPatientMale"
* entry[=].resource = PrenatalReproductivePreRiskFamilialHyperinsulinismPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePreRiskAlpha1ADPatientMale"
* entry[=].resource = PrenatalReproductivePreRiskAlpha1ADPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalReproductivePreRiskAutosomalRecessiveSAoCSPatientMale"
* entry[=].resource = PrenatalReproductivePreRiskAutosomalRecessiveSAoCSPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalNegativeReprRiskPatientMale"
* entry[=].resource = PrenatalNegativeReprRiskPatientMale
* entry[+].fullUrl = "http://hapi-fhir-server:8080/fhir/Bundle/PrenatalGenomicReportPatientMale"
* entry[=].resource = PrenatalGenomicReportPatientMale